"""
NexusGraph — FastAPI application factory.

Exposes:
  GET  /health
  GET  /info
  GET  /openapi.json   (auto-generated by FastAPI)
  /v1/graph/*          (nodes, edges, clusters, subgraph, relations)

The built React frontend is served from /static/* when available.
"""
from __future__ import annotations

import logging
import os
import time
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.config import get_settings
from app.database import close_db, init_db
from app.routers.graph import router as graph_router
from app.routers.quantum import router as quantum_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

_START_TIME = time.time()
_FRONTEND_DIR = Path(__file__).parent.parent / "frontend" / "dist"


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    logger.info("Starting NexusGraph v%s on port %d", settings.version, settings.port)
    init_db()
    yield
    await close_db()
    logger.info("NexusGraph shut down cleanly")


def enforce_admin_token_requirement() -> None:
    """Fail fast when deployment requires an admin token but none is configured.

    Set GRAPH_REQUIRE_ADMIN_TOKEN=1 (as production docker-compose does) to make
    startup abort unless NEXUS_GRAPH_ADMIN_TOKEN holds a non-empty secret. This
    prevents shipping the write API unauthenticated by accident.
    """
    required = os.environ.get("GRAPH_REQUIRE_ADMIN_TOKEN", "").strip().lower() in {"1", "true", "yes"}
    token = os.environ.get("NEXUS_GRAPH_ADMIN_TOKEN", "").strip()
    if required and not token:
        raise RuntimeError(
            "NEXUS_GRAPH_ADMIN_TOKEN is required but not set. "
            "This deployment sets GRAPH_REQUIRE_ADMIN_TOKEN, so a non-empty admin "
            "token must be provided to protect graph write endpoints. Set the "
            "NEXUS_GRAPH_ADMIN_TOKEN environment variable to a secret value."
        )


def create_app() -> FastAPI:
    enforce_admin_token_requirement()
    settings = get_settings()

    app = FastAPI(
        title="NexusGraph",
        version=settings.version,
        description=(
            "Knowledge Graph API — entity nodes, weighted edges, Louvain community detection, "
            "and ego-graph subgraphs over the NexusConsult entity database."
        ),
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── API routes ────────────────────────────────────────────────────────────
    app.include_router(graph_router)
    app.include_router(quantum_router)

    # ── Quantum-aware exception handlers ──────────────────────────────────────
    @app.exception_handler(StarletteHTTPException)
    async def http_exception_handler(request: Request, exc: StarletteHTTPException):
        if "/quantum/" in request.url.path:
            from app.routers.quantum import get_backend as _qb
            detail = exc.detail
            err_msg = detail.get("error", str(detail)) if isinstance(detail, dict) else str(detail)
            return JSONResponse(
                status_code=exc.status_code,
                content={"error": err_msg, "fallback_used": _qb().fallback_used},
            )
        # Preserve standard FastAPI {"detail": ...} envelope for non-quantum routes
        return JSONResponse(
            status_code=exc.status_code,
            content={"detail": exc.detail},
        )

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(request: Request, exc: RequestValidationError):
        if "/quantum/" in request.url.path:
            from app.routers.quantum import get_backend as _qb
            first_msg = exc.errors()[0].get("msg", "Validation error") if exc.errors() else "Validation error"
            return JSONResponse(
                status_code=422,
                content={"error": str(first_msg), "fallback_used": _qb().fallback_used},
            )
        # Preserve standard FastAPI {"detail": ...} envelope for non-quantum routes
        return JSONResponse(
            status_code=422,
            content={"detail": exc.errors()},
        )

    # ── /health ───────────────────────────────────────────────────────────────
    @app.get("/health", tags=["meta"], summary="Health check")
    async def health():
        return JSONResponse({
            "status": "ok",
            "service": "nexus-graph",
            "version": settings.version,
            "uptime_seconds": round(time.time() - _START_TIME, 2),
        })

    # ── /info ─────────────────────────────────────────────────────────────────
    @app.get("/info", tags=["meta"], summary="Service info")
    async def info():
        return JSONResponse({
            "service": "nexus-graph",
            "version": settings.version,
            "port": settings.port,
            "description": "Bounded knowledge graph API with focused traversal and Louvain summaries",
            "documentationPath": "/docs/graph",
            "endpoints": [
                {"method": "GET",  "path": "/health",                  "auth": False, "description": "Health check"},
                {"method": "GET",  "path": "/info",                    "auth": False, "description": "Service info"},
                {"method": "GET",  "path": "/openapi.json",            "auth": False, "description": "OpenAPI spec"},
                {"method": "GET",  "path": "/v1/graph/nodes",          "auth": False, "description": "List entity nodes (bounded pagination)"},
                {"method": "GET",  "path": "/v1/graph/nodes/{id}",     "auth": False, "description": "Single node detail + neighbors"},
                {"method": "GET",  "path": "/v1/graph/edges",          "auth": False, "description": "Bounded edges between a set of node IDs"},
                {"method": "GET",  "path": "/v1/graph/clusters",       "auth": False, "description": "Bounded Louvain community summaries"},
                {"method": "GET",  "path": "/v1/graph/subgraph/{id}",  "auth": False, "description": "Focused bounded graph with progressive depth"},
                {"method": "POST", "path": "/v1/graph/relations",      "auth": True,  "description": "Create manual relation (admin)"},
            ],
        })

    # ── Serve React frontend (built static files) ─────────────────────────────
    if _FRONTEND_DIR.exists():
        app.mount("/assets", StaticFiles(directory=str(_FRONTEND_DIR / "assets")), name="assets")

        @app.get("/", include_in_schema=False)
        async def serve_index():
            return FileResponse(str(_FRONTEND_DIR / "index.html"))

        @app.get("/{full_path:path}", include_in_schema=False)
        async def serve_spa(full_path: str):
            file_path = _FRONTEND_DIR / full_path
            if file_path.exists() and file_path.is_file():
                return FileResponse(str(file_path))
            return FileResponse(str(_FRONTEND_DIR / "index.html"))

    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn
    settings = get_settings()
    uvicorn.run("app.main:app", host="0.0.0.0", port=settings.port, reload=settings.debug)
