"""
NexusGraph — FastAPI application factory.

Exposes:
  GET  /health
  GET  /info
  GET  /openapi.json   (auto-generated by FastAPI)
  /v1/graph/*          (nodes, edges, clusters, subgraph, relations)

The built React frontend is served from /static/* when available.
"""
from __future__ import annotations

import logging
import time
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from app.config import get_settings
from app.database import close_db, init_db
from app.routers.graph import router as graph_router

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

_START_TIME = time.time()
_FRONTEND_DIR = Path(__file__).parent.parent / "frontend" / "dist"


@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    logger.info("Starting NexusGraph v%s on port %d", settings.version, settings.port)
    init_db()
    yield
    await close_db()
    logger.info("NexusGraph shut down cleanly")


def create_app() -> FastAPI:
    settings = get_settings()

    app = FastAPI(
        title="NexusGraph",
        version=settings.version,
        description=(
            "Knowledge Graph API — entity nodes, weighted edges, Louvain community detection, "
            "and ego-graph subgraphs over the NexusConsult entity database."
        ),
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
        lifespan=lifespan,
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── API routes ────────────────────────────────────────────────────────────
    app.include_router(graph_router)

    # ── /health ───────────────────────────────────────────────────────────────
    @app.get("/health", tags=["meta"], summary="Health check")
    async def health():
        return JSONResponse({
            "status": "ok",
            "service": "nexus-graph",
            "version": settings.version,
            "uptime_seconds": round(time.time() - _START_TIME, 2),
        })

    # ── /info ─────────────────────────────────────────────────────────────────
    @app.get("/info", tags=["meta"], summary="Service info")
    async def info():
        return JSONResponse({
            "service": "nexus-graph",
            "version": settings.version,
            "port": settings.port,
            "description": "Knowledge graph API with Louvain clustering and React force-graph UI",
            "endpoints": [
                {"method": "GET",  "path": "/health",                  "auth": False, "description": "Health check"},
                {"method": "GET",  "path": "/info",                    "auth": False, "description": "Service info"},
                {"method": "GET",  "path": "/openapi.json",            "auth": False, "description": "OpenAPI spec"},
                {"method": "GET",  "path": "/v1/graph/nodes",          "auth": False, "description": "List entity nodes (paginated)"},
                {"method": "GET",  "path": "/v1/graph/nodes/{id}",     "auth": False, "description": "Single node detail + neighbors"},
                {"method": "GET",  "path": "/v1/graph/edges",          "auth": False, "description": "Edges between a set of node IDs"},
                {"method": "GET",  "path": "/v1/graph/clusters",       "auth": False, "description": "Louvain community clusters (10 min cache)"},
                {"method": "GET",  "path": "/v1/graph/subgraph/{id}",  "auth": False, "description": "Ego-graph radius 2"},
                {"method": "POST", "path": "/v1/graph/relations",      "auth": True,  "description": "Create manual relation (admin)"},
            ],
        })

    # ── Serve React frontend (built static files) ─────────────────────────────
    if _FRONTEND_DIR.exists():
        app.mount("/assets", StaticFiles(directory=str(_FRONTEND_DIR / "assets")), name="assets")

        @app.get("/", include_in_schema=False)
        async def serve_index():
            return FileResponse(str(_FRONTEND_DIR / "index.html"))

        @app.get("/{full_path:path}", include_in_schema=False)
        async def serve_spa(full_path: str):
            file_path = _FRONTEND_DIR / full_path
            if file_path.exists() and file_path.is_file():
                return FileResponse(str(file_path))
            return FileResponse(str(_FRONTEND_DIR / "index.html"))

    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn
    settings = get_settings()
    uvicorn.run("app.main:app", host="0.0.0.0", port=settings.port, reload=settings.debug)
